source "$(dirname "$0")/plugins/init.sh"
source "$(dirname "$0")/fzf.sh"
source "$(dirname "$0")/env.sh"
source "$(dirname "$0")/aliases.sh"
source "$(dirname "$0")/functions.sh"
source "$(dirname "$0")/variables.sh"
source "$(dirname "$0")/paths.sh"
