theme = "catppuccin_mocha"

[editor]
true-color = true
file-picker.hidden = true
line-number = "relative"
cursorline = false
color-modes = true
auto-pairs = true
auto-save = true
auto-completion = true
bufferline = "multiple"
completion-replace = true
auto-format = true
scroll-lines = 1
workspace-lsp-roots = [".project", ".git", "package.json", ".venv", "build", "CMakeLists.txt"]
soft-wrap.enable = true
preview-completion-insert = false
popup-border = "all"
insert-final-newline = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
skip-levels = 1

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.smart-tab]
supersede-menu = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
left = [
  "mode",
  "spinner",
  "file-type",
  "file-name",
  "file-modification-indicator",
]
center = []
separator = "|"
right = [
  "position",
  "spacer",
  "diagnostics",
  "workspace-diagnostics",
  "version-control",
  "register"
]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
Z = { Z = ":wq", Q = ":q" }
G = "goto_file_end"
K = "hover"
g = { c = { c = "toggle_comments" } }
D = "kill_to_line_end"
Y = [
  "goto_line_start",
  "select_mode",
  "goto_line_end",
  "yank",
  "exit_select_mode",
  "collapse_selection",
]

"A-k" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
"A-j" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_down",
  "paste_before",
]

tab = "move_parent_node_end"
S-tab = "move_parent_node_start"


[keys.select]
g = { c = "toggle_comments", b="toggle_block_comments" }
"A-k" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
"A-j" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_down",
  "paste_before",
]
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"

[keys.insert]
C-h = "delete_word_backward"
"C-backspace" = "delete_word_backward"
"C-space" = "completion"
S-tab = "move_parent_node_start"


[keys.normal.space]
s = ":w"
f = { f = "file_picker", n = ":new", g = "global_search", r = ":config-reload" }
o = { g = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w80% -h80% -E lazygit", d = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w80% -h80% -E lazydocker", f = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w80% -h80% -E yazi", t=":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w80% -h80% -E zsh" }
b = { p = "goto_previous_buffer", n = "goto_next_buffer", o = ":buffer-close-others", b = "buffer_picker", d = ":buffer-close" }
c = { a = "code_action", r = "rename_symbol", d = "diagnostics_picker", D = "workspace_diagnostics_picker", f = ":format", s = "symbol_picker", S = "workspace_symbol_picker", j="jumplist_picker" }
O = "no_op"
k = "no_op"
j = "no_op"
S = "no_op"
d = "no_op"
D = "no_op"
a = "no_op"
r = "no_op"
F = "no_op"
# g = "no_op"
"'" = "no_op"
"h" = "no_op"
