[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

[[language]]
name = "sql"
language-servers = [ "sql-language-server" ]

[[language]]
name = "html"
indent={tab-width=4,unit="    "}
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]

[[language]]
name = "css"
indent={tab-width=4,unit="    "}
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]


[[language]]
name = "javascript"
indent={tab-width=4,unit="    "}
language-servers = ["typescript-language-server"]

[[language]]
name = "jsx"
indent={tab-width=4,unit="    "}
language-servers = ["typescript-language-server", "tailwindcss-ls" ]

[[language]]
name = "tsx"
indent={tab-width=4,unit="    "}
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

[[language]]
name = "svelte"
indent={tab-width=4,unit="    "}
language-servers = [ "svelteserver", "tailwindcss-ls" ]

[[language]]
name = "yaml"
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "yaml"] }


[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name="c"
indent={tab-width=4,unit="\t"}
auto-format=true
formatter = { command = "clang-format" }

[[language]]
name = "python"
auto-format = true
language-servers = ["pylsp","pyright","ruff"]
formatter = {command = "black" , args = ["--line-length","88","--quiet","-"]}

[language-server.pylsp.config.pylsp]
plugins.black.enabled = true
plugins.pylint.enabled = true
plugins.pyflakes.enabled = true
plugins.pyls_mypy.enabled = true
plugins.pyls_mypy.live_mode = false
plugins.isort.enabled = true
plugins.rope_autoimport.enabled = true
plugins.ruff.enabled = true
