theme = "catppuccin_mocha"

[editor]
true-color = true
file-picker.hidden = false
line-number = "relative"
cursorline = true
color-modes = true
auto-pairs = true
bufferline = "multiple"
scroll-lines = 1
workspace-lsp-roots = [".project", ".git", "package.json", ".venv", "build"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
left = ["mode", "spinner", "file-type", "file-name"]
center = []
separator = "|"
right = [
	"position",
	"spacer",
	"diagnostics",
	"workspace-diagnostics",
	"version-control",
]

[keys.normal]
Z = { Z = ":wq", Q = ":q" }
G = "goto_file_end"

[keys.normal.space]
s = ":w"
f = { f = "file_picker" , n = ":new", g="global_search"}
o = { s = "symbol_picker", g = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w80% -h80% -E lazygit", d = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w80% -h80% -E lazydocker" }
O = "no_op"
b={ b = "goto_previous_buffer", n = "goto_next_buffer", o=":buffer-close-others", e="buffer_picker", d=":buffer-close"}
